name: cellpylib3d_dev_env

channels:
  - conda-forge

dependencies:
  - python=3.11.16
  - matplotlib=3.11.2
  - numpy=2.4.6
  - sphinx=3.5.4
  - pytest
  - pytest-cov
  - pandas=2.2.3
  - spyder-kernels=3.0.2
  - pip
  - pip:
      - sphinx-rtd-theme
      - sphinx-prompt==1.4.0
      - cellpylib==2.4.0
